//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistem_Informasi_BEM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBSIBEMEntities : DbContext
    {
        public DBSIBEMEntities()
            : base("name=DBSIBEMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dtlrapat> dtlrapats { get; set; }
        public virtual DbSet<msanggotabem> msanggotabems { get; set; }
        public virtual DbSet<msdeparteman> msdepartemen { get; set; }
        public virtual DbSet<msformatksk> msformatksks { get; set; }
        public virtual DbSet<msjabatan> msjabatans { get; set; }
        public virtual DbSet<msnew> msnews { get; set; }
        public virtual DbSet<msperiode> msperiodes { get; set; }
        public virtual DbSet<msukm_hima> msukm_hima { get; set; }
        public virtual DbSet<trka> trkas { get; set; }
        public virtual DbSet<trlaporanksk> trlaporanksks { get; set; }
        public virtual DbSet<trnotulensi> trnotulensis { get; set; }
        public virtual DbSet<trpengajuandana> trpengajuandanas { get; set; }
        public virtual DbSet<trrapat> trrapats { get; set; }
    }
}
