//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistem_Informasi_BEM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class dtlnotulensi
    {
        public int idnotulensi { get; set; }
        public int idanggota { get; set; }
        [Required(ErrorMessage = "Keterangan tidak boleh kosong")]
        [StringLength(50)]
        public string keterangan { get; set; }
    
        public virtual msanggotabem msanggotabem { get; set; }
        public virtual trnotulensi trnotulensi { get; set; }
    }
}
