//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistem_Informasi_BEM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtlrapat 
    {
        public int idrapat { get; set; }
        public int idanggota { get; set; }
        public string keterangan { get; set; }
    
        public virtual msanggotabem msanggotabem { get; set; }
        public virtual trrapat trrapat { get; set; }
    }
}
