//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistem_Informasi_BEM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaporanKa
    {
        public int idlaporan { get; set; }
        public string jeniskas { get; set; }
        public Nullable<int> nominal { get; set; }
        public string nama { get; set; }
        public Nullable<int> total { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
