//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistem_Informasi_BEM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class msanggotabem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public msanggotabem()
        {
            this.dtlnotulensis = new HashSet<dtlnotulensi>();
            this.trkas = new HashSet<trka>();
            this.trpengajuandanas = new HashSet<trpengajuandana>();
        }
    
        public int idanggota { get; set; }
        public Nullable<int> iddepartemen { get; set; }
        public Nullable<int> idjabatan { get; set; }
        public Nullable<int> idperiode { get; set; }
        public string nama { get; set; }
        public string nim { get; set; }
        public string alamat { get; set; }
        public string no_telp { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<int> status { get; set; }
        public string creaby { get; set; }
        public Nullable<System.DateTime> creadate { get; set; }
        public string modiby { get; set; }
        public Nullable<System.DateTime> modidate { get; set; }
        public string foto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtlnotulensi> dtlnotulensis { get; set; }
        public virtual msdeparteman msdeparteman { get; set; }
        public virtual msjabatan msjabatan { get; set; }
        public virtual msperiode msperiode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trka> trkas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trpengajuandana> trpengajuandanas { get; set; }
    }
}
