//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistem_Informasi_BEM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class msanggotabem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public msanggotabem()
        {
            this.dtlrapats = new HashSet<dtlrapat>();
            this.trkas = new HashSet<trka>();
            this.trpengajuandanas = new HashSet<trpengajuandana>();
        }
        public int idanggota { get; set; }
        [Required(ErrorMessage = "Departemen tidak boleh kosong")]
        public Nullable<int> iddepartemen { get; set; }
        [Required(ErrorMessage = "Jabatan tidak boleh kosong")]
        public Nullable<int> idjabatan { get; set; }
        [Required(ErrorMessage = "Periode tidak boleh kosong")]
        public Nullable<int> idperiode { get; set; }
        [Required(ErrorMessage = "Nama tidak boleh kosong")]
        [StringLength(50)]
        [RegularExpression(@"^[a-zA-Z\s]+$", ErrorMessage = "Masukan Hanya Alphabet")]
        public string nama { get; set; }
        [Required(ErrorMessage = "NIM tidak boleh kosong")]
        [StringLength(10)]
        [RegularExpression(@"^[0-9]*$", ErrorMessage = "Masukan Hanya Angka")]
        public string nim { get; set; }
        [Required(ErrorMessage = "Alamat tidak boleh kosong")]
        [StringLength(255)]
        [DataType(DataType.MultilineText)]
        public string alamat { get; set; }
        [Required(ErrorMessage = "Telepon tidak boleh kosong")]
        [StringLength(15)]
        [RegularExpression(@"^[0-9]*$", ErrorMessage = "Masukan Hanya Angka")]
        public string no_telp { get; set; }
        [Required(ErrorMessage = "Email tidak boleh kosong")]
        [StringLength(50)]
        [RegularExpression(@"^[a-zA-z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$", ErrorMessage = "Format email tidak valid")]
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<int> status { get; set; }
        public string creaby { get; set; }
        public Nullable<System.DateTime> creadate { get; set; }
        public string modiby { get; set; }
        public Nullable<System.DateTime> modidate { get; set; }
        public string foto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtlrapat> dtlrapats { get; set; }
        public virtual msdeparteman msdeparteman { get; set; }
        public virtual msjabatan msjabatan { get; set; }
        public virtual msperiode msperiode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trka> trkas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trpengajuandana> trpengajuandanas { get; set; }
    }
}
