//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistem_Informasi_BEM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trka
    {
        public int idkas { get; set; }
        public Nullable<int> idanggota { get; set; }
        public Nullable<int> nominal { get; set; }
        public string jeniskas { get; set; }
        public Nullable<int> status { get; set; }
        public string creaby { get; set; }
        public Nullable<System.DateTime> creadate { get; set; }
        public string modiby { get; set; }
        public Nullable<System.DateTime> modidate { get; set; }
        public string uplod_bukti { get; set; }
    
        public virtual msanggotabem msanggotabem { get; set; }
    }
}
