//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistem_Informasi_BEM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class trlaporanksk : uploadFile
    {
        public int idlpksk { get; set; }
        public Nullable<int> idukm_hima { get; set; }
        [Required(ErrorMessage = "Nama tidak boleh kosong")]
        public string namaberkas { get; set; }
        public string keterangan { get; set; }
        public Nullable<int> status { get; set; }
        public string komentar { get; set; }
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy HH:mm}")]
        public Nullable<System.DateTime> tglpresent { get; set; }
        public string creaby { get; set; }
        public Nullable<System.DateTime> creadate { get; set; }
        public string modiby { get; set; }
        public Nullable<System.DateTime> modidate { get; set; }
    
        public virtual msukm_hima msukm_hima { get; set; }
    }
}
