//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistem_Informasi_BEM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class trpengajuandana
    {
        public int id { get; set; }
        public Nullable<int> idanggota { get; set; }
        [Required(ErrorMessage = "Event tidak boleh kosong")]
        public string @event { get; set; }
        [Required(ErrorMessage = "Tujuan tidak boleh kosong")]
        public string tujuan { get; set; }
        [DisplayFormat(DataFormatString = "{0:N}", ApplyFormatInEditMode = true)]
        public Nullable<int> jumlah { get; set; }
        public Nullable<int> status { get; set; }
        public string creaby { get; set; }
        public Nullable<System.DateTime> creadate { get; set; }
        public string modiby { get; set; }
        public Nullable<System.DateTime> modidate { get; set; }
        public string kepada { get; set; }
        public string Bukti_kirim { get; set; }
    
        public virtual msanggotabem msanggotabem { get; set; }
    }
}
